version: build {build}

image:
  - Ubuntu

build:
  verbosity: minimal

branches:
  only:
  - master

init:
  - git config --global core.autocrlf input

build_script:
  - dotnet tool restore
  - dotnet publish src/Bolero.TodoMVC.Client/ -o $PWD/publish/

on_success:
  - pwsh -file ./tools/gh-pages.ps1 -env appveyor

environment:
  GH_TOKEN:
    secure: dhFy1eZoqG4QPkKTuLFxix7QQMxaIyIpYjkvTU3CukYZz1CEOJeHfBSaT8tkPsGL
